# Generated by Django 4.0.6 on 2022-07-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin - Can delete members'), ('Regular', "Regular - Can't delete members")], default='Regular', max_length=20, verbose_name='role'),
        ),
    ]
